### ISSUE TITLE
Cloud hk.

### ISSUE THREAD

**Issue by bestesankaynagi** [CankayaUniversity/ceng-407-408-2021-2022-Restaurant-Reviews-According-To-Geographical-Location#9]
Cloud sistem ekleme ve clouddan fetch etme kısmını düzenleyebilir misin?

**Comment by TheNewCoder01** [comment]
o Kısımlaxrı güncelliyorum

**Comment by TheNewCoder01** [comment]
Cloud'a ekleme kısımlarını güncelliyorum
